/*****+---*----**-*-------*---***-**-*--***-*--*****************************
 *
 *  Homework #:05
 *
 *  Academic Integrity Statement:
 *
 *  I have not used source code obtained from any other unauthorized source,
 *  either modified or unmodified.  Neither have I provided access to my code
 *  to another. The effort I am submitting is my own original work.
 *
 *  Program Description: Uses a series of randomly generated codes with parameters input by the user in order to calculate the maximum value of the digits produced
 *
 ******+---*----**-*-------*---***-**-*--***-*--****************************/
#include <stdlib.h>
#include <math.h>

#define LOOPMAX 20

void input(int* seedValue, int* powerLimit);
void processCodes(int seedValue, int powerLimit, int *max, int *min);
int generateCode(int ceiling);
int calcSum(int code);
void printOutput(int max, int maxIndex, int min, int minIndex);

int main(void)
{
  int seedValue;
  int powerLimit;
  int max;
  int min;
  int maxIndex;
  int minIndex;

  input(&seedValue, &powerLimit);
  srand(seedValue);

  processCodes(seedValue, powerLimit, &max, &min);

  printOutput()
  return 0;
}

/*****+-*-----**--*-*-*-*-*-*--*---****--**-*--*****************************
 *
 *  Function Information
 *
 *  Name of Function: processCodes
 *
 *  Function Return Type: void
 *
 *  Parameters (list data type, name, and comment one per line):
 *    1. int seedValue - the value of the seed input by the user
 *    2. int powerLimit - the value of the power limit input by the user
 *    3. int* max - pointer to the maximum sum produced
 *    4. int* min - pointer to the minimum sum produced
 *    5. int* maxIndex - pointer to the index of the maximum sum
 *    6. int* minIndex - pointer to the index of the minimum sum
 *  Function Description: Creates and sums a total of LOOPMAX codes and finds the maximum and minimum
 *
 ******+-*-----**--*-*-*-*-*-*--*---****--**-*--****************************/
void processCodes(int seedValue, int powerLimit, int* max, int* min, int* maxIndex, int* minIndex)
{ 
  int i;
  int sum;
  int code;

  code = generateCode(powerLimit);
  *max = calcSum(code);
  *min = calcSum(code);

  for(i = 0; i < LOOPMAX - 1; i++)
  {
    code = generateCode(powerLimit);
    
    sum = calcSum(code);

    if(sum > *max)
    {
      *max = sum;
    } else if(sum < *min)
    {
      *min = sum;
    }
  }
  printf("\nMax: %d", *max);
  printf("\nMin: %d", *min);

}

/*****+-*-----**--*-*-*-*-*-*--*---****--**-*--*****************************
 *
 *  Function Information
 *
 *  Name of Function: calcSum
 *
 *  Function Return Type:int
 *
 *  Parameters (list data type, name, and comment one per line):
 *    1. int code - represents the code to be processsed
 *
 *  Function Description: Calculates the total of the digits of a number (code)
 *
 ******+-*-----**--*-*-*-*-*-*--*---****--**-*--****************************/

int calcSum(int code)
{
  int sum;
  sum = 0;

  do
  {
    sum += code % 10;
    code /= 10;
  } while (code > 0);

  return sum;
}

/*****+-*-----**--*-*-*-*-*-*--*---****--**-*--*****************************
 *
 *  Function Information
 *
 *  Name of Function: input
 *
 *  Function Return Type: void
 *
 *  Parameters (list data type, name, and comment one per line):
 *    1.int* seedValue - the seed input by the user
 *    2.int* powerLimit - the power limit (base 10) input by the user
 *
 *  Function Description: Takes input from the user and stores it in variables
 *
 ******+-*-----**--*-*-*-*-*-*--*---****--**-*--****************************/

void input(int* seedValue, int* powerLimit)
{
  printf("Enter the seed value -> ");
  scanf("%d", seedValue);
  printf("Enter the power of 10 limit -> ");
  scanf("%d", powerLimit);
  *powerLimit = (int) pow(10, *powerLimit);
}

/*****+-*-----**--*-*-*-*-*-*--*---****--**-*--*****************************
 *
 *  Function Information
 *
 *  Name of Function: generateCode
 *
 *  Function Return Type: int
 *
 *  Parameters (list data type, name, and comment one per line):
 *    1.int ceiling - represents the highest number that can be generated by the code 
 *
 *  Function Description: Generates a random code of maximum 'ceiling'
 *
 ******+-*-----**--*-*-*-*-*-*--*---****--**-*--****************************/

int generateCode(int ceiling)
{
  return (rand() % (ceiling + 1));
}

void printOutput(int max, int maxIndex, int min, int minIndex)
{
  printf("\n-=-=-=-=-=-=-=-=-=-=-=-");
  printf("\nSmallest Sum #%d:%4d", minIndex, min);
  printf("\nLargest Sum #%d:%4d", maxIndex, max);
  printf("\n-=-=-=-=-=-=-=-=-=-=-=-";)
}